### ISSUE TITLE
Can HyperStyle be trained for StyleGAN3 out of the shelf?

### ISSUE THREAD

**Issue by ouhenio** [yuval-alaluf/hyperstyle#1]
As the title says, is it possible to use the training script with a pre-trained SG3 or it will require some adjustments from my side?

By the way, thanks a lot for all your work with inversion!

**Comment by yuval-alaluf** [comment]
The code currently doesn't support StyleGAN3, so it will require some adjustments. 
The reason for this is that I feel like adding support for a generator that is not understood too well yet (in my opinion), may complicate things. 
For example, it is not entirely clear how to perform latent space manipulations within SG3's latent space, which may not hold the same disentanglement properties as SG2. This would also require training new editing directions for the various editing techniques, which takes a decent amount of work. 
Therefore, I felt like holding off on adding support for SG3 in this repo (along with the other inversion works) is the right decision at this time.
I will say that I have begun running experiments with ReStyle + SG3 and the reconstruction results do look promising (on par with those of SG2). However, I have not yet had a chance to play around with editing within the latent space.

**Comment by ouhenio** [comment]
Thank you for your answer! I didn't expect it to be so thorough, so I really appreciate that you took the time to do it. 

I'll entertain myself then trying to make it work :)

Good luck with your future research!
