### ISSUE TITLE
KeyError: 'opts'

### ISSUE THREAD

**Issue by tmlderm** [yuval-alaluf/hyperstyle#10]
Trying to run inference
```
python scripts/inference.py \
--exp_dir=test_data \
--checkpoint_path=pt/disney_princess.pt \
--data_path=test_data \
--test_batch_size=4 \
--test_workers=4 \
--n_iters_per_batch=5 \
--load_w_encoder \
--w_encoder_checkpoint_path pt/faces_w_encoder.pt
```

I got error:
```
Traceback (most recent call last):
  File "scripts/inference.py", line 108, in <module>
    run()
  File "scripts/inference.py", line 32, in run
    net, opts = load_model(test_opts.checkpoint_path, update_opts=test_opts)
  File "./utils/model_utils.py", line 14, in load_model
    opts = ckpt['opts']
KeyError: 'opts'
```

I try to run any script and all of them failed. Could you please provide actual example of how to apply any style?

**Comment by yuval-alaluf** [comment]
If you are trying to run inference and perform domain adaptation, you should be using the `run_domain_adaptation` script.  All the details are provided in the README: https://github.com/yuval-alaluf/hyperstyle#domain-adaptation 

Basically, your checkpoint path is incorrect. Follow the example in the README and it should work.
