### ISSUE TITLE
AssertionError: Cannot infer latent code when e4e isn't loaded

### ISSUE THREAD

**Issue by tmlderm** [yuval-alaluf/hyperstyle#11]
```

python editing/inference_face_editing.py \
--exp_dir=/path/to/experiment \
--checkpoint_path=pt/hyperstyle_ffhq.pt \
--data_path=test_data \
--test_batch_size=4 \
--test_workers=4 \
--n_iters_per_batch=3 \
--edit_directions=age,pose,smile \
```

```

Loading HyperStyle from checkpoint: pt/hyperstyle_ffhq.pt
Loading dataset for ffhq_hypernet
  0%|                                                                                                                                   | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "editing/inference_face_editing.py", line 109, in <module>
    run()
  File "editing/inference_face_editing.py", line 58, in run
    result_batch = run_on_batch(input_cuda, net, latent_editor, opts)
  File "editing/inference_face_editing.py", line 93, in run_on_batch
    y_hat, _, weights_deltas, codes = run_inversion(inputs, net, opts)
  File "./utils/inference_utils.py", line 22, in run_inversion
    return_weight_deltas_and_codes=True)
  File "./models/hyperstyle.py", line 70, in forward
    assert self.opts.load_w_encoder, "Cannot infer latent code when e4e isn't loaded."
AssertionError: Cannot infer latent code when e4e isn't loaded.
```

Please help to run it

**Comment by yuval-alaluf** [comment]
You probably need to add the flag `--load_w_encoder` when running the script. I will update the README to include this in the example.

**Comment by Winnie202** [comment]
> You probably need to add the flag `--load_w_encoder` when running the script. I will update the README to include this in the example.
i add the flag ,do not work ,why?

Traceback (most recent call last):
  File "scripts/train.py", line 32, in <module>
    main()
  File "scripts/train.py", line 19, in main
    coach = Coach(opts)
  File "./training/coach_hyperstyle.py", line 35, in __init__
    self.net = HyperStyle(self.opts).to(self.device)
  File "./models/hyperstyle.py", line 25, in __init__
    self.load_weights()
  File "./models/hyperstyle.py", line 61, in load_weights
    self.w_encoder = self.__get_pretrained_w_encoder()
  File "./models/hyperstyle.py", line 145, in __get_pretrained_w_encoder
    w_net = pSp(opts_w_encoder)
  File "./models/encoders/psp.py", line 33, in __init__
    self.load_weights()
  File "./models/encoders/psp.py", line 48, in load_weights
    self.encoder.load_state_dict(get_keys(ckpt, 'encoder'), strict=True)
  File "/home/lesmart/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for WEncoder:
        Missing key(s) in state_dict: "linear.weight", "linear.bias". 
        Unexpected key(s) in state_dict: "styles.0.convs.0.weight", "styles.0.convs.0.bias", "styles.0.convs.2.weight", "styles.0.convs.2.bias", "styles.0.convs.4.weight", "styles.0.convs.4.bias", "styles.0.convs.6.weight", "styles.0.convs.6.bias", "styles.0.linear.weight", "styles.0.linear.bias", "styles.1.convs.0.weight", "styles.1.convs.0.bias", "styles.1.convs.2.weight", "styles.1.convs.2.bias", "styles.1.convs.4.weight", "styles.1.convs.4.bias", "styles.1.convs.6.weight", "styles.1.convs.6.bias", "styles.1.linear.weight", "styles.1.linear.bias", "styles.2.convs.0.weight", "styles.2.convs.0.bias", "styles.2.convs.2.weight", "styles.2.convs.2.bias", "styles.2.convs.4.weight", "styles.2.convs.4.bias", "styles.2.convs.6.weight", "styles.2.convs.6.bias", "styles.2.linear.weight", "styles.2.linear.bias", "styles.3.convs.0.weight", "styles.3.convs.0.bias", "styles.3.convs.2.weight", "styles.3.convs.2.bias", "styles.3.convs.4.weight", "styles.3.convs.4.bias", "styles.3.convs.6.weight", "styles.3.convs.6.bias", "styles.3.convs.8.weight", "styles.3.convs.8.bias", "styles.3.linear.weight", "styles.3.linear.bias", "styles.4.convs.0.weight", "styles.4.convs.0.bias", "styles.4.convs.2.weight", "styles.4.convs.2.bias", "styles.4.convs.4.weight", "styles.4.convs.4.bias", "styles.4.convs.6.weight", "styles.4.convs.6.bias", "styles.4.convs.8.weight", "styles.4.convs.8.bias", "styles.4.linear.weight", "styles.4.linear.bias", "styles.5.convs.0.weight", "styles.5.convs.0.bias", "styles.5.convs.2.weight", "styles.5.convs.2.bias", "styles.5.convs.4.weight", "styles.5.convs.4.bias", "styles.5.convs.6.weight", "styles.5.convs.6.bias", "styles.5.convs.8.weight", "styles.5.convs.8.bias", "styles.5.linear.weight", "styles.5.linear.bias", "styles.6.convs.0.weight", "styles.6.convs.0.bias", "styles.6.convs.2.weight", "styles.6.convs.2.bias", "styles.6.convs.4.weight", "styles.6.convs.4.bias", "styles.6.convs.6.weight", "styles.6.convs.6.bias", "styles.6.convs.8.weight", "styles.6.convs.8.bias", "styles.6.linear.weight", "styles.6.linear.bias", "styles.7.convs.0.weight", "styles.7.convs.0.bias", "styles.7.convs.2.weight", "styles.7.convs.2.bias", "styles.7.convs.4.weight", "styles.7.convs.4.bias", "styles.7.convs.6.weight", "styles.7.convs.6.bias", "styles.7.convs.8.weight", "styles.7.convs.8.bias", "styles.7.convs.10.weight", "styles.7.convs.10.bias", "styles.7.linear.weight", "styles.7.linear.bias", "styles.8.convs.0.weight", "styles.8.convs.0.bias", "styles.8.convs.2.weight", "styles.8.convs.2.bias", "styles.8.convs.4.weight", "styles.8.convs.4.bias", "styles.8.convs.6.weight", "styles.8.convs.6.bias", "styles.8.convs.8.weight", "styles.8.convs.8.bias", "styles.8.convs.10.weight", "styles.8.convs.10.bias", "styles.8.linear.weight", "styles.8.linear.bias", "styles.9.convs.0.weight", "styles.9.convs.0.bias", "styles.9.convs.2.weight", "styles.9.convs.2.bias", "styles.9.convs.4.weight", "styles.9.convs.4.bias", "styles.9.convs.6.weight", "styles.9.convs.6.bias", "styles.9.convs.8.weight", "styles.9.convs.8.bias", "styles.9.convs.10.weight", "styles.9.convs.10.bias", "styles.9.linear.weight", "styles.9.linear.bias", "styles.10.convs.0.weight", "styles.10.convs.0.bias", "styles.10.convs.2.weight", "styles.10.convs.2.bias", "styles.10.convs.4.weight", "styles.10.convs.4.bias", "styles.10.convs.6.weight", "styles.10.convs.6.bias", "styles.10.convs.8.weight", "styles.10.convs.8.bias", "styles.10.convs.10.weight", "styles.10.convs.10.bias", "styles.10.linear.weight", "styles.10.linear.bias", "styles.11.convs.0.weight", "styles.11.convs.0.bias", "styles.11.convs.2.weight", "styles.11.convs.2.bias", "styles.11.convs.4.weight", "styles.11.convs.4.bias", "styles.11.convs.6.weight", "styles.11.convs.6.bias", "styles.11.convs.8.weight", "styles.11.convs.8.bias", "styles.11.convs.10.weight", "styles.11.convs.10.bias", "styles.11.linear.weight", "styles.11.linear.bias", "styles.12.convs.0.weight", "styles.12.convs.0.bias", "styles.12.convs.2.weight", "styles.12.convs.2.bias", "styles.12.convs.4.weight", "styles.12.convs.4.bias", "styles.12.convs.6.weight", "styles.12.convs.6.bias", "styles.12.convs.8.weight", "styles.12.convs.8.bias", "styles.12.convs.10.weight", "styles.12.convs.10.bias", "styles.12.linear.weight", "styles.12.linear.bias", "styles.13.convs.0.weight", "styles.13.convs.0.bias", "styles.13.convs.2.weight", "styles.13.convs.2.bias", "styles.13.convs.4.weight", "styles.13.convs.4.bias", "styles.13.convs.6.weight", "styles.13.convs.6.bias", "styles.13.convs.8.weight", "styles.13.convs.8.bias", "styles.13.convs.10.weight", "styles.13.convs.10.bias", "styles.13.linear.weight", "styles.13.linear.bias", "latlayer1.weight", "latlayer1.bias", "latlayer2.weight", "latlayer2.bias".

**Comment by yuval-alaluf** [comment]
What was the path you used for the WEncoder?
