### ISSUE TITLE
Train custom generator to domain adaptation

### ISSUE THREAD

**Issue by alexeyskov** [yuval-alaluf/hyperstyle#13]
Dear authors, you provide a great SOTA approach. But it is not very clear from the repo how to train custom generator for use in a run_domain_adaptation.py script.
I tried to use pre-trained Sketch generator to fine-tune it by this repo https://github.com/rosinality/stylegan2-pytorch on my data, but weights are not suitable.
Please tell me, what I need to do to train the generator for the script run_domain_adaptation.py on my custom data?

**Comment by yuval-alaluf** [comment]
Our generators were obtained from StyleGAN-NADA (https://github.com/rinongal/StyleGAN-nada). You can train your custom generator there and load them into our domain adaptation script.
