### ISSUE TITLE
Export this model to ONNX

### ISSUE THREAD

**Issue by AAYUSH-SWAMI** [yuval-alaluf/hyperstyle#17]
Hi, I was trying to export this model to onnx but when I searched the colab notebook I found out that there is no Class defined with (nn,Module) or the model definition which is not there so I further searched and opened the 'model.py' which contain too many classes with (nn.Module). Since I am a beginner, I have very less knowledge about pytorch, onnx, ML models, etc. I have just started working on ML and working on a project which require converting to onnx. Please help. I am using this model just for fun learning and testing the viability of my project.

**Comment by yuval-alaluf** [comment]
Unfortunately, I am not familiar with ONNX. If you want to export with ONNX, looking through the notebook is not enough since this only contains a very high-level code for performing inference. 
If you are unfamiliar with ONNX, I would start with a simpler codebase to convert since we do have a lot of classes/networks in this codebase.

**Comment by AAYUSH-SWAMI** [comment]
Thank you for your reply. Can you suggest any simple codebase to start
with? I have tried but most of them contain more than one class.

**Comment by yuval-alaluf** [comment]
I would try looking at basic ONNX tutorials to start off with. I am unfamiliar with this myself so that would be where I would start.

**Comment by AAYUSH-SWAMI** [comment]
Thanks for your email

**Comment by FangliangBai** [comment]
@AAYUSH-SWAMI Hi, I am also doing ONNX converting but I got different errors. Have you successfully converted it? If yes, could you share your solution please, it is very much appreciated : )

**Comment by AAYUSH-SWAMI** [comment]
> @AAYUSH-SWAMI Hi, I am also doing ONNX converting but I got different errors. Have you successfully converted it? If yes, could you share your solution please, it is very much appreciated : )

I have tried many methods but I wasn't fully successful but I was able to generate .onnx file of that model but couldn't verify it in onnx runtime.

import torch.onnx
torch.onnx.export(model,
                  input,
                  "model.onnx",
                  export_params=True,
                  opset_version=10)

But it throws UserWarning most of the time {
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:2359: UserWarning: _floordiv_ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  _verify_batch_size([input.size(0) * input.size(1) // num_groups, num_groups] + list(input.size()[2:]))
/usr/local/lib/python3.7/dist-packages/torch/onnx/symbolic_opset9.py:1934: UserWarning: ONNX export unsqueeze with negative axis -1 might cause the onnx model to be incorrect. Negative axis is not supported in ONNX. Axis is converted to 1 based on input shape at export time. Passing an tensor of different rank in execution will be incorrect.
  "Passing an tensor of different rank in execution will be incorrect.")
/usr/local/lib/python3.7/dist-packages/torch/onnx/symbolic_opset9.py:1934: UserWarning: ONNX export unsqueeze with negative axis -1 might cause the onnx model to be incorrect. Negative axis is not supported in ONNX. Axis is converted to 2 based on input shape at export time. Passing an tensor of different rank in execution will be incorrect.
  "Passing an tensor of different rank in execution will be incorrect.")
}

**Comment by FangliangBai** [comment]
> 

Hi, @AAYUSH-SWAMI, thank you very much for replying to me! I think I did something similar, but I got an error which stopped me to convert. The error message was like:

> Traceback (most recent call last):
  File "/media/kent/DISK2/GitHub_Repos/HyperStyle/scripts/onnx_conversion.py", line 147, in <module>
    run()
  File "/media/kent/DISK2/GitHub_Repos/HyperStyle/scripts/onnx_conversion.py", line 63, in run
    torch.onnx.export(decoder, inputs, "decoder.onnx", export_params=True, 
  File "/media/kent/DISK2/virtualenv_gallery/e2id/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/media/kent/DISK2/virtualenv_gallery/e2id/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/media/kent/DISK2/virtualenv_gallery/e2id/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/media/kent/DISK2/virtualenv_gallery/e2id/lib/python3.8/site-packages/torch/onnx/utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/media/kent/DISK2/virtualenv_gallery/e2id/lib/python3.8/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/media/kent/DISK2/virtualenv_gallery/e2id/lib/python3.8/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/media/kent/DISK2/virtualenv_gallery/e2id/lib/python3.8/site-packages/torch/onnx/utils.py", line 1032, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/media/kent/DISK2/virtualenv_gallery/e2id/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 172, in wrapper
    return fn(g, *args, **kwargs)
  File "/media/kent/DISK2/virtualenv_gallery/e2id/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py", line 1281, in _convolution
    raise RuntimeError("Unsupported: ONNX export of convolution for kernel "
RuntimeError: Unsupported: ONNX export of convolution for kernel of unknown shape.

I couldn't figure out what makes my code different from yours. If not making trouble, could you please share your converting script so I can have more details to debug or even try exporting to onnx using your script? Thank you very much!

In case you want to have quick glance, I also paste my code below. As you can see, I just want to export the generator.

```py
def run():
    test_opts = TestOptions().parse()

    out_path_results = os.path.join(test_opts.exp_dir, 'inference_results')
    out_path_coupled = os.path.join(test_opts.exp_dir, 'inference_coupled')

    os.makedirs(out_path_results, exist_ok=True)
    os.makedirs(out_path_coupled, exist_ok=True)

    # update test options with options used during training
    # net, opts = load_model(test_opts.checkpoint_path, update_opts=test_opts)

    ckpt = torch.load(test_opts.checkpoint_path, map_location='cpu')
    opts = ckpt['opts']
    decoder = Generator(opts['output_size'], 512, 8, channel_multiplier=2)

    def get_keys(d, name):
        if 'state_dict' in d:
            d = d['state_dict']
        d_filt = {k[len(name) + 1:]: v for k, v in d.items() if k[:len(name)] == name}
        return d_filt

    decoder.load_state_dict(get_keys(ckpt, 'decoder'), strict=True)
    decoder.eval()

    # Convert decoder to ONNX model
    dummy_input = [torch.randn(1, 18, 512)]
    # decoder.cuda()
    inputs = (dummy_input, {'input_is_latent': True, 'randomize_noise': False})

    with torch.no_grad():
        torch.onnx.export(decoder, inputs, "decoder.onnx", export_params=True,
                          input_names=['input'], output_names=['output'],
                          dynamic_axes={'input': {0: 'batch_size'}, 'output': {0: 'batch_size'}},
                          verbose=True)
```

**Comment by AAYUSH-SWAMI** [comment]
I am not a professional and I don't have much knowledge about it so if you still want to have a look at my edited colab notebook I can share it with you but it is a mess and your code look much neater than mine could ever be. So I just have experimented some methods to export the model and some of the code partly work so it is no where complete. So I will share my colab here but I don't think you will like so open with caution ;)
[Copy_of_poolformer_demo.zip](https://github.com/yuval-alaluf/hyperstyle/files/8002044/Copy_of_poolformer_demo.zip)
