### ISSUE TITLE
Problem while editing afhq-wild via StyleCLIP

### ISSUE THREAD

**Issue by P2Oileen** [yuval-alaluf/hyperstyle#18]
Hello, this is really a great repo! I'm trying to reproduce your interesting demo. I used the afhq-wild weights provided in this repo, but failed to get the edited results. The result image doesn't seem to be changed when prompt text is changed. My testing options  are as follows. I sincerely hope to get your help and tell me where the problem is. Thank you so much!

```
{
    "alpha": 4.1,
    "beta": 0.18,
    "delta_i_c": "editing/styleclip/global_directions/ffhq/fs3.npy",
    "exp_dir": "results/",
    "n_images": null,
    "neutral_text": "a tiger",
    "num_alphas": 1,
    "num_betas": 1,
    "s_statistics": "editing/styleclip/global_directions/ffhq/S_mean_std",
    "stylegan_size": 512,
    "stylegan_truncation": 1.0,
    "stylegan_truncation_mean": 4096,
    "stylegan_weights": "pretrained_models/afhqwild.pt",
    "target_text": "a lion",
    "text_prompt_templates": "editing/styleclip/global_directions/templates.txt",
    "weight_deltas_path": "results/"
}
```

The images are as follows:
input
![image](https://user-images.githubusercontent.com/26021786/147463360-4146775e-7b95-40b9-8c4e-c863e8495929.png)
output
![image](https://user-images.githubusercontent.com/26021786/147463372-319074ad-23b5-4c1f-bb2a-7bba4378d8e8.png)

**Comment by yuval-alaluf** [comment]
You probably need to play with the `alpha` and `beta` values. Different edits may be different editing strengths, for example. 
Try running the script with a range of values for each parameter and try seeing if you are able to pinpoint the parameters needed for performing your edit.
