### ISSUE TITLE
gender direction

### ISSUE THREAD

**Issue by rainsoulsrx** [yuval-alaluf/hyperstyle#19]
Hi, nice work. 
I wonder is it possible to provide a gender direction? I use gender direction here: https://github.com/genforce/interfacegan
but the results did not change  a lot just as follows. Is there anything wrong with me?
![image](https://user-images.githubusercontent.com/24955512/147470695-57bb6851-1530-439d-afb5-2c36d1e0a914.png)

**Comment by yuval-alaluf** [comment]
The InterFaceGAN implementation uses StyleGAN1 generators for learning the directions so those directions will not work here. 
You can train your own gender direction by following their procedure: 
1. Generate 500,000 samples using SG2. 
2. For each image, apply a pretrained gender classifier to obtain an attribute score. 
3. Use InterFaceGAN's `train_boundary` function to learn the direction. 

For computing the attribute score, you can use the classifier from [AnyCostGAN](https://github.com/mit-han-lab/anycost-gan) which has a classifier for 40 different attributes including gender.
