### ISSUE TITLE
Access Denied when Downloading Pre-trained Model Weights in Colab Notebook

### ISSUE THREAD

**Issue by ajndkr** [yuval-alaluf/hyperstyle#2]
When running the inference notebook on google colab, the `gdown` command fails due to access denied. 

Error message recommends that the access should be changed to "Anyone with the link".

**Comment by yuval-alaluf** [comment]
It seems like we may have reached the quota limit for Google Drive. This weekend I will work on finding a solution to this quota limit. 
What you can do for now is make a local copy to your own Drive account and update the download ID. 
In any case, the limit seems to get fixed an hour or so after reaching it.

**Comment by ajndkr** [comment]
cool! thanks for the quick response.
