### ISSUE TITLE
randomize_noise=False

### ISSUE THREAD

**Issue by wonjunn** [yuval-alaluf/hyperstyle#20]
As I know, previous works(pSp, e4e, ReStyle...) used randomize_noise=True.

I wonder why you changed randomize_noise from True to False. Thank you.

**Comment by yuval-alaluf** [comment]
If you're performing inversion you may not want to randomize the noise input into StyleGAN. That is why I disabled it here, but visually the difference is quite negligible. I just felt that logically, it made more sense to disable it.
