### ISSUE TITLE
in Editing Faces with InterFaceGAN 

### ISSUE THREAD

**Issue by Winnie202** [yuval-alaluf/hyperstyle#22]
age.pt,  pose.pt, smile.pt ， How do I get them?  I use hyperstyle to train my dataset，I want to get my .pt files，What should I do？

**Comment by yuval-alaluf** [comment]
These are provided in the repo: 
https://github.com/yuval-alaluf/hyperstyle/tree/main/editing/interfacegan_directions

**Comment by Winnie202** [comment]
> These are provided in the repo: https://github.com/yuval-alaluf/hyperstyle/tree/main/editing/interfacegan_directions

i know that，but i want to get new .pt file on my hyperstyle which trained with my own datasets. what should i do ?  thank you!

**Comment by yuval-alaluf** [comment]
We follow the official implementation of InterFaceGAN. We generate 500,000 images from StyleGAN2 and use a pretrained attribute classifier to obtain an attribute score for each latent. We then train an SVM to separate between the two extreme points of the latents (i.e., latents with the highest and lowest scores).
Basically, you can use the function in the following link: https://github.com/genforce/interfacegan/blob/acec139909fb9aad41fbdbbbde651dfc0b7b3a17/utils/manipulator.py#L12

This function receives your sampled latents and their corresponding scores and returns the boundary for that editing direction.

**Comment by alinacccc** [comment]
> 

Have you get new .pt? I want more other .pt file
