### ISSUE TITLE
Is style mixing between 2 people possible with HyperStyle?

### ISSUE THREAD

**Issue by kuprel** [yuval-alaluf/hyperstyle#23]
Love your StyleGAN inversion work!  With pSp and e4e (and ReStyle too I think), it is possible to mix styles between two people since they use the same generator network.  But for HyperStyle, the weights of the generator depend on the person.  Is style mixing still possible for HyperStyle?

**Comment by kuprel** [comment]
After closer inspection, it seems like the `weights_delta` computed by HyperStyle can be alternately interpreted as modifying the styles, and then the styles modify the conv weights as they do in the original StyleGAN.  Specifically at this line: https://github.com/yuval-alaluf/hyperstyle/blob/83047be63543c873a37e89938a266d9c32cad0e6/models/stylegan2/model.py#L240

which can be refactored as

`weight = self.scale * self.weight * ((1 + weights_delta) * style)`

Basically with HyperStyle, instead of having a single 1D styles tensor per image, the styles are now a list of 4D and 1D tensors (1D for the layers where styles are not multiplied by 1 + weights_delta)

Then it follows that the encoder and generator networks can be factored into 2 separate networks with the generator network containing only the weights from the original person-independent StyleGAN.  The encoder would compute a list of 4D and 1D tensor styles, and the generator would take as input a list of 4D and 1D tensor styles.  Then style mixing could work as normal, by mixing `(1 + weights_delta_i) * styles_i` and `(1 + weights_delta_j) * styles_j` for people `i` and `j`.

**Comment by Manhha3010** [comment]
> kuprel

Can you implement this ?
