### ISSUE TITLE
Is there a way to fine tune the inversion?

### ISSUE THREAD

**Issue by SleyAI** [yuval-alaluf/hyperstyle#24]
Hello,
I'm currently testing your implementation by inferencing FFHQ images. It works really well but there is still a noticeable difference between the original image and the image from the inversion. I tried to set n_iters_per_batch to a higher value but this leads to blurred images. Any hint would be really helpful!

**Comment by yuval-alaluf** [comment]
You could possibly perform a few steps of HyperStyle and then perform PTI to optimize the generator a bit. This hybrid approach could give you better reconstructions at only a small increase in the inference time. 
PTI when starting from an initial W latent runs for about a minute per image. If we first run HyperStyle and then optimize the generator, I am sure you can bring that down to about 15 seconds or so.
