### ISSUE TITLE
Huggingface Spaces

### ISSUE THREAD

**Issue by AK391** [yuval-alaluf/hyperstyle#25]
Hi, would you be interested in sharing a web demo on Huggingface Spaces for hyperstyle?

It would make this model more accessible as it would allow people to try out the model directly from the browser. Some other recent machine learning model repos have set up Spaces for easy access:

github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/akhaliq/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

Spaces is completely free, and I can help setup a Gradio Space. Here are some getting started instructions if you'd prefer to do it yourself: https://huggingface.co/blog/gradio-spaces

**Comment by yuval-alaluf** [comment]
Hi @AK391! 
A demo for HyperStyle on Huggingface Spaces does sound interesting. Unfortunately, I do not know how much time I have right now to work on this myself. 
I'll get this task in my backlog for the future, but I do hope to check it out soon. Thanks for the recommendation!
