### ISSUE TITLE
weird results

### ISSUE THREAD

**Issue by sususheep0** [yuval-alaluf/hyperstyle#27]
Hi, I am a totally new starter and my question could be too simple to you.
When I run the inference.py and I get this werid result, could you please tell me the reason?
My cmd line is:

python scripts/inference.py --exp_dir=exp_0308_001/ --checkpoint_path=pretrained_models/hyperstyle_ffhq.pt --data_path=./exp_data/ --test_batch_size=8 --test_workers=8 --n_iters_per_batch=5 --load_w_encoder

**Input:
![Euro_0001](https://user-images.githubusercontent.com/101183370/157411004-319df436-c806-4db0-9115-7b26274a047b.jpg)
Output:**
![Euro_0001](https://user-images.githubusercontent.com/101183370/157410939-9510655c-c001-429e-b008-456b3ef3e325.jpg)

**Comment by yuval-alaluf** [comment]
You need to make sure you align the image before running inference.

**Comment by sususheep0** [comment]
Thank you for your patient reply.
