### ISSUE TITLE
Training time of HyperStyle

### ISSUE THREAD

**Issue by ai-alanov** [yuval-alaluf/hyperstyle#28]
Hi,

I'm currently trying to train HyperStyle from scratch for FFHQ. I use the training command suggested in the "Training HyperStyle" section in the readme. I run it on one A100 Nvidia GPU. From training, I see that 1k steps take approximately one hour. So, as I understand to finish the full training (500k steps), I need to wait 500 hours (20 days). Is it right? 

Could you please share how much time you spent training HyperStyle and which resources you used? 

Thanks!

**Comment by yuval-alaluf** [comment]
The parameter for `max_steps` is a little misleading here so apologies for the confusion. 
Our models weren't actually trained for that many steps. The FFHQ model was trained for 120,000 steps.

**Comment by ai-alanov** [comment]
Thank for the clarification! 
So, should the training time be approximately 5 days on one GPU? Or maybe you use some tricks to speed up the training process (multi-gpu, etc.)?

**Comment by yuval-alaluf** [comment]
We used a single P40 GPU which I think is a bit slower than the A100 if I'm not mistaken. So I think our training took around a week. But around 5-8 days sounds about right.

**Comment by ai-alanov** [comment]
Thank you very much for your prompt reply!
