### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_models/hyperstyle_ffhq.pt'

### ISSUE THREAD

**Issue by AlexanderKozhevin** [yuval-alaluf/hyperstyle#3]
```
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_models/hyperstyle_ffhq.pt'
```

when trying to run
```
if not os.path.exists(EXPERIMENT_ARGS['model_path']) or os.path.getsize(EXPERIMENT_ARGS['model_path']) < 1000000:
    print(f'Downloading HyperStyle model for {experiment_type}...')
    os.system(hyperstyle_download_command)
    # if google drive receives too many requests, we'll reach the quota limit and be unable to download the model
    if os.path.getsize(EXPERIMENT_ARGS['model_path']) < 1000000:
        raise ValueError("Pretrained model was unable to be downloaded correctly!")
    else:
        print('Done.')
else:
    print(f'HyperStyle model for {experiment_type} already exists!')
```

**Comment by yuval-alaluf** [comment]
Hi, 
I was not able to recreate this error just now.  
I believe this is most likely to be something related to either: 
1. An incorrect CODE_DIR (it should be pointing to the directory `hyperstyle`)
2. Failure to correctly download the model. 

I believe there are ways to improve the downloading process of the notebook and plan on sitting on it this weekend.  
Until then, I hope that restarting the runtime may help.

**Comment by yuval-alaluf** [comment]
Hi,
I've just made a commit simplifying the inference notebook (or at least I hope 😄 ). Thanks for the patience!
