### ISSUE TITLE
The results of inference is weird

### ISSUE THREAD

**Issue by lovejing0306** [yuval-alaluf/hyperstyle#31]
Hi, I run the inference.py and I get werid result.

The original images as bellow, these images has aligned:
![7_dahuzi_12_1](https://user-images.githubusercontent.com/14770340/164419458-890faa6e-7085-4b64-8692-ed3a7c9edfb3.jpg)
![17_dahuzi_12_1](https://user-images.githubusercontent.com/14770340/164419575-2aa094ce-1a94-4668-81c0-bc63e6630fa0.jpg)

My cmd line is:
```
exp_dir=outputs
checkpoint_path=checkpoints/hyperstyle_ffhq.pt
w_encoder_checkpoint_path=pretrained_models/faces_w_encoder.pt
data_path=outputs/align/aligned
test_batch_size=2
test_workers=2
n_iters_per_batch=5


python3 -u scripts/inference.py \
--exp_dir=$exp_dir \
--checkpoint_path=$checkpoint_path \
--load_w_encoder \
--w_encoder_checkpoint_path=$w_encoder_checkpoint_path \
--data_path=$data_path \
--test_batch_size=$test_batch_size \
--test_workers=$test_workers \
--n_iters_per_batch=$n_iters_per_batch \
--save_weight_deltas
```

The results of output is werid.
![7_dahuzi_12_1](https://user-images.githubusercontent.com/14770340/164420112-cf8c673d-65a8-47aa-b829-36318a9a0e92.jpg)
![17_dahuzi_12_1](https://user-images.githubusercontent.com/14770340/164420148-71f2a8f4-68f9-4c88-a23f-689c46e34dd5.jpg)

Can you help me get the correct result?

**Comment by yuval-alaluf** [comment]
I just ran those two images in the colab notebook and got the following results (the original is on the left and the reconstruction after 5 steps is on the right): 
![download](https://user-images.githubusercontent.com/37438467/164758070-bcbfbb72-4217-47f2-b2ea-d0c64a8466cb.png)
![download (1)](https://user-images.githubusercontent.com/37438467/164758073-1c316f91-2e22-4d7e-8e3f-709d5d07fb3a.png)

The step-by-step results (obtained by running the actual inference.py script) returns the following: 
![IM1](https://user-images.githubusercontent.com/37438467/164758322-9aa5937f-5d4d-41e0-9b1b-85dca82c1ae4.jpeg)
![im2](https://user-images.githubusercontent.com/37438467/164758329-b1273814-b797-4d93-9697-ddb0dbf02348.jpeg)


So it seems like it should work. I can't find something wrong with your parameters. Is your code identical to the original code?

**Comment by lovejing0306** [comment]
Thanks for your reply, I clone your project again, the result of inference is normal. I don not know why. It is very a amazing. @yuval-alaluf
