### ISSUE TITLE
Given a face with a certain hairstyle, how to test the w value of the hairstyle

### ISSUE THREAD

**Issue by c1a1o1** [yuval-alaluf/hyperstyle#32]
Given a face with a certain hairstyle, how to test the w value of the hairstyle

**Comment by yuval-alaluf** [comment]
Can you clarify what you mean by the w value of the hairstyle?

**Comment by c1a1o1** [comment]
Sorry for the misunderstanding caused. Taking age as an example, given a face that is not in the data set, how to calculate the w value corresponding to his current age

**Comment by yuval-alaluf** [comment]
Typically when we refer to `w` we are referring to the style vector that is used to generate the image. What do you mean by `w` value of the current age? `w` doesn't take a single value and isn't related to a specific attribute.
