### ISSUE TITLE
Questions about initial w dimension

### ISSUE THREAD

**Issue by kasim0226** [yuval-alaluf/hyperstyle#33]
UPDATED: I think I get somethning wrong. The both latent codes are 18*512. Am I right?

====================
Thank you for your great work.

From paper, I thought you use e4e to get initial w, so the dimension will be 18*512.
However, when I run ./editing/styleclip/edit.py, the loaded latent code is 1*512. Did you average them or I got something misunderstandning?

Looking dorward to your reply.

**Comment by yuval-alaluf** [comment]
You're correct. However, you can still edit the images in W+ with dimension 18x512 with the latent code in W that has dimension 1x512. The change will simply operate on all the 18 vectors individually and you'll get the expected result. 

> The both latent codes are 18*512. Am I right?

Generally, the edit direction will be of dimension 1x512. If it is of dimension 18x512, it may be that it was replicated 18 times but all vectors should be identical. In either case, even though the dimensions aren't exact, you will still be able to perform the edit.
