### ISSUE TITLE
Eyeglasses from InterfaceGAN?

### ISSUE THREAD

**Issue by ghost** [yuval-alaluf/hyperstyle#37]
Hello,

Can you add the Eyeglasses option from InterfaceGAN? Awesome work by the way!!!!

Thanks!

**Comment by yuval-alaluf** [comment]
You can find various InterFaceGAN directions from the AnyCostGAN repo: 
https://github.com/mit-han-lab/anycost-gan#using-pre-trained-models

**Comment by ghost** [comment]
Hello,

I am sorry, but I am a bit lost. I found the code here:

https://github.com/mit-han-lab/anycost-gan/blob/master/models/__init__.py

but I dont understand how to get the InterfaceGAN glasses model from this code.

Can you help?

Thanks!

**Comment by yuval-alaluf** [comment]
After you clone their repo, you can do something like: 
```python
import models

pretrained_type = 'boundary'  # choosing from ['generator', 'encoder', 'boundary']
config_name = 'anycost-ffhq-config-f'  # replace the config name for other models
boundaries = models.get_pretrained(pretrained_type, config=config_name)
eye_glasses_boundary = boundaries['Eyeglasses']
```
I believe `boundaries` should be a dictionary mapping the name of the attribute to the boundary itself. 
Once you have the `eye_glasses_boundary` you can save this as an `npy` file and load it for editing in this repo if you would like.

**Comment by ghost** [comment]
Thank you!

**Comment by ghost** [comment]
Hello, I did as you suggested and saved the file as glasses.npy. I tried loading it in this code in Hyperstyle:

        self.interfacegan_directions = {
            'glasses': torch.load(model_paths['glasses']).cuda(),
            'age': torch.load(model_paths['age']).cuda(),
            'smile': torch.load(model_paths['smile']).cuda(),
            'pose': torch.load(model_paths['pose']).cuda()}

but I get the error: STACK_GLOBAL requires str

I am guessing I shouldnt load the numpy file with torch? How do I run inference then?

Thanks!

**Comment by ghost** [comment]
Ok, I got it working with the code below:

        self.interfacegan_directions = {
            'glasses': torch.from_numpy(numpy.load(model_paths['glasses'])).cuda(),
            'age': torch.load(model_paths['age']).cuda(),
            'smile': torch.load(model_paths['smile']).cuda(),
            'pose': torch.load(model_paths['pose']).cuda()}

I have a question though, there were 9 pictures output from running glasses.npy, but only the last two actually had glasses on. Any idea what happened?

**Comment by yuxu915** [comment]
Hi,
It seems that the pre-trained boundaries from anycostGAN are lost in their webpage, did you download them? Really hope you can share them with me, thank you!
