### ISSUE TITLE
Trouble with StyleCLIP

### ISSUE THREAD

**Issue by ghost** [yuval-alaluf/hyperstyle#39]
Hello,

When this line of code executes in edit.py:

`    stylegan_model.load_state_dict(checkpoint['g_ema'])`

I get the following errors:

```
  Message=Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "conv1.conv.blur.kernel", "convs.1.conv.blur.kernel", "convs.3.conv.blur.kernel", "convs.5.conv.blur.kernel", "convs.7.conv.blur.kernel", "convs.9.conv.blur.kernel", "convs.11.conv.blur.kernel", "convs.13.conv.blur.kernel", "convs.15.conv.blur.kernel". 
  Source=P:\HyperStyle\editing\styleclip\edit.py
  StackTrace:
  File "P:\HyperStyle\editing\styleclip\edit.py", line 61, in load_stylegan_generator
    stylegan_model.load_state_dict(checkpoint['g_ema'])
  File "P:\HyperStyle\editing\styleclip\edit.py", line 68, in run
    stylegan_model = load_stylegan_generator(args)
  File "P:\HyperStyle\editing\styleclip\edit.py", line 105, in <module> (Current frame)
    run()

```

I am using the stylegan2-ffhq-config-f.pt file you link on your page here. Any idea what might be wrong?

Thanks!

**Comment by yuval-alaluf** [comment]
Hi, 
I just redownloaded the model linked in the repo and ran the StyleCLIP code, but was unable to re-create your error (my model was loaded successfully with the original code). 
Were any changes made to the code?

**Comment by ghost** [comment]
You are correct, I made a change to the styleclip model that broke things. Thanks!
