### ISSUE TITLE
input size (non square) 

### ISSUE THREAD

**Issue by tengolagan** [yuval-alaluf/hyperstyle#45]
Hi, 

I'd like to use your method to invert a stylegan2 trained on non square images (this one actually [stylehuman](https://stylegan-human.github.io/) ). any advice ?

**Comment by yuval-alaluf** [comment]
If you would like to use HyperStyle to invert full body images, you need to make a few changes. This is what comes to mind: 
1. You'll need to first modify their Generator implementation to support the weight deltas used by HyperStyle. It seems like you will need to modify the following line to match what is used in HyperStyle: 
https://github.com/stylegan-human/StyleGAN-Human/blob/2f64159f5ce14721c292d44a53eb023b6c0a0bd2/torch_utils/models.py#L342
2. During training, we resize our outputs from (1024x1024) to (256,256) using `self.face_pool`, which is defined [here](https://github.com/yuval-alaluf/hyperstyle/blob/c6b9b4cb39badfbc1a0037476909b3fd403d780e/models/hyperstyle.py#L23). You'll want to change this to, for example, (512, 256) or something that is non-square.
3. When we pass the images to the encoder, we resize them to (256,256) as defined [here](https://github.com/yuval-alaluf/hyperstyle/blob/c6b9b4cb39badfbc1a0037476909b3fd403d780e/configs/transforms_config.py#L21). You may want to change this to a non-square size. 
    - However, if you do so, you will need to make a small alteration to the architecture of the encoder in order to resize the final feature map to `16x16`. If your inputs are of size (512,256) for example, you'll get a feature map of `32x16`, so you'll need to add another down-sampling layer in the encoder.

I think that covers the big changes. There are probably some other changes you'll need to make, but I'd start with this. 
Note that the first step is a bit involved. If you want to start with something simpler, I would recommend trying to invert first with ReStyle (the repo is [here](https://github.com/yuval-alaluf/restyle-encoder)). If you use ReStyle, you'll need to start at step 2.

Hope this helps!
