### ISSUE TITLE
Error when finetune the hypernet with hyperstyle_ffhq.pt

### ISSUE THREAD

**Issue by Zirconium2159** [yuval-alaluf/hyperstyle#48]
I follow the default setting as readme while trying to add --checkpoint_path=pretrained-models/hyperstyle_ffhq.pt in the **training** command, but it returns 

` Missing key(s) in state_dict: "refinement_blocks.0.convs.0.weight", "refinement_blocks.0.convs.0.bias", "refinement_blocks.0.convs.2.weight", "refinement_blocks.0.convs.2.bias", "refinement_blocks.0.convs.4.weight", "refinement_blocks.0.convs.4.bias", "refinement_blocks.0.convs.6.weight", "refinement_blocks.0.convs.6.bias", "refinement_blocks.0.convs.8.weight", "refinement_blocks.0.convs.8.bias", "refinement_blocks.0.linear.weight", "refinement_blocks.0.linear.bias", "refinement_blocks.0.hypernet.w1", "refinement_blocks.0.hypernet.b1", "refinement_blocks.0.hypernet.w2", "refinement_blocks.0.hypernet.b2", "refinement_blocks.2.convs.0.weight", "refinement_blocks.2.convs.0.bias", "refinement_blocks.2.convs.2.weight", "refinement_blocks.2.convs.2.bias", "refinement_blocks.2.convs.4.weight", "refinement_blocks.2.convs.4.bias", "refinement_blocks.2.convs.6.weight", "refinement_blocks.2.convs.6.bias", "refinement_blocks.2.convs.8.weight", "refinement_blocks.2.convs.8.bias", "refinement_blocks.2.linear.weight", "refinement_blocks.2.linear.bias", "refinement_blocks.2.hypernet.w1", "refinement_blocks.2.hypernet.b1", "refinement_blocks.2.hypernet.w2", "refinement_blocks.2.hypernet.b2", "refinement_blocks.3.convs.0.weight", "refinement_blocks.3.convs.0.bias", "refinement_blocks.3.convs.2.weight", "refinement_blocks.3.convs.2.bias", "refinement_blocks.3.convs.4.weight", "refinement_blocks.3.convs.4.bias", "refinement_blocks.3.convs.6.weight", "refinement_blocks.3.convs.6.bias", "refinement_blocks.3.convs.8.weight", "refinement_blocks.3.convs.8.bias", "refinement_blocks.3.linear.weight", "refinement_blocks.3.linear.bias", "refinement_blocks.3.hypernet.w1", "refinement_blocks.3.hypernet.b1", "refinement_blocks.3.hypernet.w2", "refinement_blocks.3.hypernet.b2". `

Is there any specific configuration when getting  hyperstyle_ffhq.pt you provided?

**Comment by yuval-alaluf** [comment]
This is a strange behavior.
What is the exact command you tried running?
