### ISSUE TITLE
face editting boundary

### ISSUE THREAD

**Issue by yuxu915** [yuval-alaluf/hyperstyle#49]
Hi, thanks for your brilliant work!
When I run face editing in HyperStyle, I find that the 3 boundaries have different shape, specifically, the boundary shape of 'pose' is [1, 18, 512], while 'smile' and 'age' are [1, 512]. I just wonder why is that?
Besides, I would like to try other attributes, could you please provide other boundaries?
Thank you.

**Comment by yuval-alaluf** [comment]
There is no difference in the behavior. If you have a boundary that is [1,512], the editing will simply broadcast to the dimension of the input latent which is [18, 512] so everything should work fine. 
If you want other boundaries they can be downloaded from: https://github.com/mit-han-lab/anycost-gan
You can follow the instructions in their README.

**Comment by yuxu915** [comment]
Thanks!
