### ISSUE TITLE
 Image creation from latent code

### ISSUE THREAD

**Issue by isack-ml** [yuval-alaluf/hyperstyle#50]
Good paper, thanks for the code.

I want to try a few things in latent code editing, and I'm looking for a way to create an image directly from the latent code. Any help in this regard would be of great help.
Thank you.

**Comment by yuval-alaluf** [comment]
You have a loaded generator you can generate the image using something like the following: 
```python
images, _ = self.generator([latents],
        weights_deltas=weight_deltas,
        randomize_noise=False,
        input_is_latent=True)
```
where `weight_deltas` is the output of the hypernetwork. If you don't have any weight offsets, you can simply set this argument to `None`.

**Comment by isack-ml** [comment]
Thank you.
'weights_deltas=None ' was the difficulty I had. thank you it was a great help
