### ISSUE TITLE
weights_delta in GAN Inversion

### ISSUE THREAD

**Issue by yuxu915** [yuval-alaluf/hyperstyle#51]
Hi, thanks for your great work!
to edit a real image, I'd like to save the latent code files and weights_delta files, so that I don't need to run gan inversion next time.
I save them as .npy files, however, when I try to load them, something wrong with "weights_delta"
<img width="582" alt="image" src="https://user-images.githubusercontent.com/94051337/180239993-3df30b9b-5edf-433c-9134-290aac7b0079.png">
ValueError: only one element tensors can be converted to Python scalars

Any hints would be helpful!

**Comment by yuval-alaluf** [comment]
Where in the code does your code fail? I am not sure exactly what you are trying to do here.
