### ISSUE TITLE
Using pretrained E4E models from different domain

### ISSUE THREAD

**Issue by AleksiKnuutila** [yuval-alaluf/hyperstyle#53]
Hi, and many thanks for fantastic work.

I am training a hyper style model for the first time with a custom model.

One practical question: Can I expect reasonable performance if I use a pertained E4E encoder from a domain different than my custom dataset? For example: My custom dataset contains images of buildings. Since there isn't a pretrained E4E model of buildings, can I use the pretrained model related to cars?

Many thanks!

**Comment by yuval-alaluf** [comment]
You will need to train an e4e WEncoder on your domain. This shouldn't take more than a handful of days to train and then you can train HyperStyle over this same dataset using your trained WEncoder.

**Comment by zhihongp** [comment]
A StyleGAN needs to trained for that domain before the WEncoder.  Am I right?
