### ISSUE TITLE
Is it possible to convert images to different domain without adding latent directions?

### ISSUE THREAD

**Issue by kasim0226** [yuval-alaluf/hyperstyle#57]
Thank you for your great work.
Is to possible to convert images to different domain and did not adding latent directions to latect codes?
For example, pSp can generate a front-facing face from a given input image and generate photo-realistic face images from ambiguous sketch images

I am wondering Hyperstyle can do the same thing?

If it is possilbe, should I modeified your codes? or I just need to change data path?

Looking forward to your reply.
![擷取](https://user-images.githubusercontent.com/5126656/189851657-f60d2925-da9c-47cb-aba7-e907c7cbebb4.JPG)

**Comment by yuval-alaluf** [comment]
You should be able to add support for pSp-like tasks by mainly changing the dataset (to your desired source and target domains) and modifying the losses as appropriate. 
Other than that, I believe the image-to-image tasks should work with hyperstyle, although I have not tried this myself.

**Comment by kasim0226** [comment]
Thank you for your reply.
I will try it

**Comment by dmangla3** [comment]
Hi @kasim0226 , just wanted to know if you were able to generate frontalized images using hyperstyle?
