### ISSUE TITLE
Is Conditional Image Synthesis possible?(segmentation map to image)

### ISSUE THREAD

**Issue by Eric07110904** [yuval-alaluf/hyperstyle#59]
Awesome works!!!
I have a question about the application of hyperstyle.
Is it possible to do an conditional image synthesis using **hyperstyle**?
For example: "segmentation map to image " in your previous PsP project.

**Comment by yuval-alaluf** [comment]
Please see my answer here: https://github.com/yuval-alaluf/hyperstyle/issues/57

**Comment by Eric07110904** [comment]
> Please see my answer here: #57

Thanks for your reply, i will close this issue.
