### ISSUE TITLE
mixing style latents

### ISSUE THREAD

**Issue by loboere** [yuval-alaluf/hyperstyle#6]
with the previous methods I could replace layers
   8 to 18 from one latent to another latent to change the style of latente1.
from 0 to 8 is the pose of the face and from 8 to 18 is lighting and texture of the face
latent 1 = 1 18 512
latent 2 = 1 18 512
mix_laten = latent1 [0: 8] + latent2 [8:18]

 
But this generator will require weights in addition to latent, I don't know how to "split" weights_deltas for mix styles, how can I mix styles?

**Comment by yuval-alaluf** [comment]
Yea, although we didn't try it out in the paper, I do believe that mixing will still work here. 
If you take a look at the [project page](https://yuval-alaluf.github.io/hyperstyle/), you can see that there are various animations showing interpolations between images. I think that this interpolation is similar to style mixing.  
What we did there was interpolation between both the latent code and the weights.
For example, 
```python
cur_vec = vectors_b * alpha + vectors_a * (1 - alpha)
cur_weight_deltas = interpolate_weight_deltas(weights_deltas_a, weights_deltas_b, alpha)
res = net.decoder([cur_vec],
                  weights_deltas=cur_weight_deltas,
                  randomize_noise=False,
                  input_is_latent=True)[0]
```
where `alpha` is your blending factor. 
So with style mixing, I think what you could do is try doing something like: 
```python
mix_latent = latent1[0: 8] + latent2[8:18]
mix_weight_deltas = deltas1[0:8] + deltas2[0:8]
```
I am not sure this would work, but this is what I would try :)
