### ISSUE TITLE
Why is this happening?

### ISSUE THREAD

**Issue by A913440** [yuval-alaluf/hyperstyle#60]
![face_image](https://user-images.githubusercontent.com/66399665/192179270-756f79ec-5f79-4f58-85e3-cdede565d52c.jpg)

**Comment by szopeno** [comment]
I am just a simple fellow user, but I got similar results when I put unaligned images as inputs. Align them first using tools from hyperstyle (e.g. in their colab notebook) and check whether the problem persists.

**Comment by yuval-alaluf** [comment]
Correct. You need to make sure to align your inputs first.
