### ISSUE TITLE
How to generate custom dataset ganspace pca.pt?

### ISSUE THREAD

**Issue by Ruye-aa** [yuval-alaluf/hyperstyle#61]
Hi, thanks your great work!
I am a newbie doing research on image editing， I want to use HyperStyle mothods to implement specific editing tasks on custom datasets.
I have run ganspace code successfully, and find some meaningful direction, but I don't know how to generate the _pca.pt [https://github.com/yuval-alaluf/hyperstyle/tree/main/editing/ganspace_directions](url)

**Comment by yuval-alaluf** [comment]
The `pca.pt` files were taken from GANSpace's official implementation. We did not do anything special ourselves to get these files.
