### ISSUE TITLE
Could you please provide the classifier used for training interfacegan directions?

### ISSUE THREAD

**Issue by ytz123456** [yuval-alaluf/hyperstyle#62]
Hi @yuval-alaluf ,thank you for the excellent work!
I am a student researching on interfacegan-like methods for face editing. I have trained my own 'age direction' and tried the one from [anycostgan](https://github.com/mit-han-lab/anycost-gan), neither of them produce baby faces as the age direction provided here. So I wonder what classifier you use for training the directions? Is it trained by yourself or is it the classifier from [anycostgan](https://github.com/mit-han-lab/anycost-gan) ? Thank you!

**Comment by ytz123456** [comment]
If the age classifier is trained by yourself, please let me know how you trained it. Thank you!

**Comment by yuval-alaluf** [comment]
We used the age classifier that I used in another one of my works (see the SAM repo [here](https://github.com/yuval-alaluf/SAM)).
The age classifier is based on the DEX age classifier and fine-tuned on the FFHQ dataset. More details are provided in the SAM paper. 
The classifier itself can be downloaded from the SAM paper.

**Comment by ytz123456** [comment]
Thank you for your reply!
