### ISSUE TITLE
LSUN Bedrooms

### ISSUE THREAD

**Issue by anandbhattad** [yuval-alaluf/hyperstyle#63]
Hi! 

Thank you for this amazing work! Did you try your method on LSUN bedrooms? 
If yes, can you please share your findings? 

Best,
Anand

**Comment by yuval-alaluf** [comment]
We did not try running on LSUN bedrooms. Due to the large size of the dataset, we were unable to download the dataset so decided not to run on it.

**Comment by anandbhattad** [comment]
How about LSUN Church? 

Thanks!

**Comment by anandbhattad** [comment]
Another question (not related to this topic): what backbone network do you use when reporting LPIPS numbers -- VGG or AlexNet? Thanks again for your time!

**Comment by yuval-alaluf** [comment]
Based on the code, it looks like AlexNet.
