### ISSUE TITLE
About the 'smile/age/pose.pt'

### ISSUE THREAD

**Issue by Suimingzhe** [yuval-alaluf/hyperstyle#64]
Thanks for your cool work!  
I want to know how you got the 'smile/age/pose.pt' ? Because I want to generate new attribute direction vectors on my custom dataset. 

Is it the folling process? If not, please tell me.

Step 1: generate images from nosies by pretrained stylegan generator.
Step 2: use the pretrained attribute classifier to compute attribute scores.
Step 3: use https://github.com/genforce/interfacegan/blob/acec139909fb9aad41fbdbbbde651dfc0b7b3a17/utils/manipulator.py#L12 to get the boundary with the generated images and computed attributr scores. 

And last question, which attribute classifier you used to compute attribute scores?
Thanks again.

**Comment by yuval-alaluf** [comment]
The process you detailed above is exactly the process we used. 
We used various attribute classifiers: 
1. For age we use the age classifier from here: https://github.com/yuval-alaluf/SAM#pretrained-models
2. For smile I believe we used the standard 40-attribute classifier trained on CelebA-HQ
3. For pose, I don't recall exactly, but the details are provided in the paper.

**Comment by Suimingzhe** [comment]
> The process you detailed above is exactly the process we used. We used various attribute classifiers:
> 
> 1. For age we use the age classifier from here: https://github.com/yuval-alaluf/SAM#pretrained-models
> 2. For smile I believe we used the standard 40-attribute classifier trained on CelebA-HQ
> 3. For pose, I don't recall exactly, but the details are provided in the paper.

Thank you for your kind reply, it is very useful for me

**Comment by alinacccc** [comment]
> 感谢您的出色工作！我想知道你是如何得到“微笑/年龄/姿势.pt”的？因为我想在我的自定义数据集上生成新的属性方向向量。
> 
> 是晃脑的过程吗？如果没有，请告诉我。
> 
> 第 1 步：通过预训练的 stylegan 生成器从 nosies 生成图像。第 2 步：使用预训练属性分类器计算属性分数。第 3 步：使用 https://github.com/genforce/interfacegan/blob/acec139909fb9aad41fbdbbbde651dfc0b7b3a17/utils/manipulator.py#L12 获取与生成的图像和计算出的归因分数的边界。
> 
> 最后一个问题，您使用哪个属性分类器来计算属性分数？再次感谢。

你好 我也想训练新的超平面 想知道你用的什么属性分类器 来打分啊？
