### ISSUE TITLE
Pretrained Generator does not accept "weights_deltas" as a valid keyword

### ISSUE THREAD

**Issue by Sinjini15** [yuval-alaluf/hyperstyle#66]
Hi, I'm just playing around with your code and want to pass a random set of weights to the generator during inference.

I load your model as:

```
model_path = EXPERIMENT_ARGS['model_path']
net, opts = load_model(model_path, update_opts={"w_encoder_checkpoint_path": EXPERIMENT_ARGS['w_encoder_path']})
```

then I call the decoder as

```
decoder = net.decoder
```

This calls the pretrained StyleGAN2 generator that you provide. However, when I want to pass some latent code + weights to the generator as follows:

```
adapted_image, _ = decoder([y], weights_deltas=average_weights, randomize_noise = True, return_latents = False, input_is_latent = True)
```

I get this error:

```
TypeError: forward() got an unexpected keyword argument 'weights_deltas'
```

I am confused because the forward pass in the generator definition has `weights_deltas` as a defined keyword. How to fix this?

**Comment by yuval-alaluf** [comment]
Hi, were any other changes made to the code? This should work if no other changes were made. Can you make sure that the `decoder` object is indeed the one from the modified StyleGAN2 generator?

**Comment by Sinjini15** [comment]
Hey! I made no other changes but as you suspected I had some import issues regarding the correct generator. I fixed those and it worked :)
