### ISSUE TITLE
Training for different domain

### ISSUE THREAD

**Issue by zhihongp** [yuval-alaluf/hyperstyle#67]
It is a follow up question to #53.  To train one for the whole AFHQ dataset (not only AFHQ wild like in pre-trained), it should start from training a domain-specific StyleGAN first, then an e4e WEncoder, and lastly your HyperStyle model, right?

**Comment by yuval-alaluf** [comment]
Correct :)

**Comment by zhihongp** [comment]
Thanks.  I used pre-trained one from NVIDIA so that helps
