### ISSUE TITLE
About editing of AFHQW using StyleCLIP global-directions

### ISSUE THREAD

**Issue by zhihongp** [yuval-alaluf/hyperstyle#68]
I have tried the default script (used for FFHQ) but no effect on AFHQW editing.  My guess is the settings of delta_i_c and s_statistics are not properly set.  How could we duplicate the AFHQW editing as included in the paper.  Thanks

**Comment by yuval-alaluf** [comment]
You may need to play a lot with the alpha and beta parameters in StyleCLIP. Sometimes with StyleCLIP's global directions, you need test out a lot of parameters to get a combination that behaves well.

**Comment by zhihongp** [comment]
I found out that you need to compute fs3.py using code provided by StyleCLIP for a new domain.  It takes 10 hours to finish and after that it's work as I wanted.  Tweaking alpha and beta is needed too
