### ISSUE TITLE
Out-of-Domain Images

### ISSUE THREAD

**Issue by tommycwh** [yuval-alaluf/hyperstyle#69]
Thank you very much for your interesting work! I read the discussion from the paper about HyperStyle generalizing well to out-of-domain images, and I am wondering how this is done in practice. 

Let's say, I have a generator G that is trained on dataset A. Now, I want to do inversion to G using images from another dataset B. Datasets A and B are about the same type of objects (e.g., faces), but are very likely from different domains. Is it appropriate to train HyperStyle on dataset A and then do inversion on dataset B, or should I train HyperStyle on dataset B too?

**Comment by yuval-alaluf** [comment]
You can try taking the first approach (training on A and inverting B), but the results may not be satisfactory. If you want to get the best results, your best bet is to train on the second dataset as well. Or train two different models, one for each domain.
