### ISSUE TITLE
"Cannot infer latent code when e4e isn't loaded."

### ISSUE THREAD

**Issue by charliewang789** [yuval-alaluf/hyperstyle#7]
Hi when i run the code, I got following error in line 70 of hyperstyle.py.
assert self.opts.load_w_encoder, "Cannot infer latent code when e4e isn't loaded."

Did i miss anything?

**Comment by yuval-alaluf** [comment]
Hi, did you make sure to set `load_w_encoder` to True and set `w_encoder_checkpoint_path` to the correct path to the pretrained W encoder?

**Comment by charliewang789** [comment]
thank you for the quick response, and that worked.

Is there another script that can generate newer hairstyle, or age as illustrated in the picture from paper?

**Comment by yuval-alaluf** [comment]
Sure. Once you run the inference script (make sure to save the weight deltas using the `save_weight_deltas` flag), you can go to the `edit.py` script under `editing/styleclip`. There you can try a bunch of different target texts related to hair style. Some more details are provided in the readme. 
Please note that the authors of StyleCLIP noted that drastic changes to hair style (e.g. color) may not work well when using the global editing direction.

**Comment by charliewang789** [comment]
Thx.
