### ISSUE TITLE
Train new dataset based on pre-trained HyperStyle model

### ISSUE THREAD

**Issue by Herbertkid** [yuval-alaluf/hyperstyle#73]
Hi Yuval-alaluf,
I want to train my dataset based on your pre-trained model, how can i do that?
when I set the checkpoint to the 'hyperstyle_ffhq.pt' file, it has an error:
RuntimeError: Error(s) in loading state_dict for SharedWeightsHyperNetResNet:
	Missing key(s) in state_dict: "refinement_blocks.0.convs.0.weight", "refinement_blocks.0.convs.0.bias", "refinement_blocks.0.convs.2.weight", "refinement_blocks.0.convs.2.bias", "refinement_blocks.0.convs.4.weight", "refinement_blocks.0.convs.4.bias", "refinement_blocks.0.convs.6.weight", "refinement_blocks.0.convs.6.bias", "refinement_blocks.0.convs.8.weight", "refinement_blocks.0.convs.8.bias", "refinement_blocks.0.linear.weight", "refinement_blocks.0.linear.bias", "refinement_blocks.0.hypernet.w1", "refinement_blocks.0.hypernet.b1", "refinement_blocks.0.hypernet.w2", "refinement_blocks.0.hypernet.b2", "refinement_blocks.2.convs.0.weight", "refinement_blocks.2.convs.0.bias", "refinement_blocks.2.convs.2.weight", "refinement_blocks.2.convs.2.bias", "refinement_blocks.2.convs.4.weight", "refinement_blocks.2.convs.4.bias", "refinement_blocks.2.convs.6.weight", "
Unexpected key(s) in state_dict: "refinement_blocks.14.output.1.weight", "refinement_blocks.14.output.1.bias", "refinement_blocks.15.output.1.weight", "refinement_blocks.15.output.1.bias", "refinement_blocks.17.output.1.weight", "refinement_blocks.17.output.1.bias", "refinement_blocks.18.output.1.weight", "refinement_blocks.18.output.1.bias", "refinement_blocks.20.output.1.weight", "refinement_blocks.20.output.1.bias", "refinement_blocks.21.output.1.weight", "refinement_blocks.21.output.1.bias", "refinement_blocks.23.output.1.weight", "refinement_blocks.23.output.1.bias", "refinement_blocks.24.output.1.weight", "refinement_blocks.24.output.1.bias". 
	size mismatch for refinement_blocks.14.convs.4.weight: copying a param with shape torch.Size([512, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for refinement_blocks.14.convs.4.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for refinement_blocks.15.convs.4.weight: copying a param with shape torch.Size([512, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for refinement_blocks.15.convs.4.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for refinement_blocks.17.convs.4.weight: copying a param with shape torch
Br

**Comment by yuval-alaluf** [comment]
It seems like there is a mismatch between the parameters you have defined and the StyleGAN generator you are trying to run with. Can you provide me the parameters and the output size of your generator?
