### ISSUE TITLE
Pretrained W-Encoders pt file provided doesn't match the WEncoder class

### ISSUE THREAD

**Issue by CV-118** [yuval-alaluf/hyperstyle#74]
I want to use pretrained model provided to perform editing, and i excute following code 

python editing/inference_face_editing.py \
--exp_dir=/data/workspace/hyperstyle/experiment \
--checkpoint_path=experiment/checkpoints/hyperstyle_ffhq.pt \
--data_path=/data/workspace/hyperstyle/experiment/imgs/ \
--test_batch_size=4 \
--test_workers=4 \
--n_iters_per_batch=3 \
--edit_directions=age,pose,smile \
--factor_range=5 \
--load_w_encoder \
--w_encoder_checkpoint_path=experiment/checkpoints/faces_w_encoder.pt

but I got 

RuntimeError: Error(s) in loading state_dict for WEncoder:                                                                                                                                                               Missing key(s) in state_dict: "input_layer.0.weight", "input_layer.1.weight", "input_layer.1.bias", "input_layer.1.running_mean", "input_layer.1.running_var", "input_layer.2.weight", "linear.weight", "linear.bias", "body.0.res_layer.0.weight", "body.0.res_layer.0.bias", "body.0.res_layer.0.running_mean", "body.0.res_layer.0.running_var", "body.0.res_layer.1.weight", "body.0.res_layer.2.weight", "body.0.res_layer.3.weight", "body.0.res_layer.4.weight", "body.0.res_layer.4.bias", "body.0.res_layer.4.running_mean", "body.0.res_layer.4.running_var", "body.0.res_layer.5.fc1.weight", "body.0.res_layer.5.fc2.weight", "body.1.res_layer.0.weight", "body.1.res_layer.0.bias", "body.1.res_layer.0.running_mean", "body.1.res_layer.0.running_var", "body.1.res_layer.1.weight", "body.1.res_layer.2.weight", "body.1.res_layer.3.weight", "body.1.res_layer.4.weight", "body.1.res_layer.4.bias", "body.1.res_layer.4.running_mean", "body.1.res_layer.4.running_var", "body.1.res_layer.5.fc1.weight", "body.1.res_layer.5.fc2.weight", "body.2.res_layer.0.weight", "body.2.res_layer.0.bias", "body.2.res_layer.0.running_mean", "body.2.res_layer.0.running_var", "body.2.res_layer.1.weight", "body.2.res_layer.2.weight", "body.2.res_layer.3.weight", "body.2.res_$ayer.4.weight", "body.2.res_layer.4.bias", "body.2.res_layer.4.running_mean", "body.2.res_layer.4.running_var", "body.2.res_layer.5.fc1.weight", "body.2.res_layer.5.fc2.weight", "body.3.shortcut_layer.0.weight", "body.3.shortcut_layer.1.weight", "body.3.shortcut_layer.1.bias", "body.3.shortcut_layer.1.running_mean", "body.3.shortcut_layer.1.running_var", "body.3.res_layer.0.weight", "body.3.res_layer.0.bias", "body.3.res_layer.0.running_mean", "body.3.res_layer.0.running_var", "body.3.res_layer.1.weight", "body.3.res_layer.2.weight", "body.3.res_layer.3.weight", "body.3.res_layer.4.weight", "body.3.res_layer.4.bias", "body.3.res_layer.4.running_mean", "body.3.res_layer.4.running_var", "body.3.res_layer.5.fc1.weight", "body.3.res_layer.5.fc2.weight", "body.4.res_layer.0.weight", "body.4.res_layer.0.bias", "body.4.res_layer.0.running_mean", "body.4.res_layer.0.running_var", "body.4.res_layer.1.weight", "body.4.res_layer.2.weight", "body.4.res_layer.3.weight", "body.4.res_layer.4.weight", "body.4.res_layer.4.bias", "body.4.res_layer.4.running_mean", "body.4.res_layer.4.running_var", "body.4.res_layer.5.fc1.weight", "body.4.res_layer.5.fc2.weight", "body.5.res_layer.0.weight", "body.5.res_layer.0.bias", "body.5.res_layer.0.running_mean",
"body.5.res_layer.0.running_var", "body.5.res_layer.1.weight", "body.5.res_layer.2.weight", "body.5.res_layer.3.weight", "body.5.res_layer.4.weight", "body.5.res_layer.4.bias", "body.5.res_layer.4.running_mean", "body.5.res_layer.4.running_var", "body.5.res_layer.5.fc1.weight", "body.5.res_layer.5.fc2.weight", "body.6.res_layer.0.weight", "body.6.res_layer.0.bias", "body.6.res_layer.0.running_mean", "body.6.res_layer.0.running_var", "body.6.res_layer.1.weight", "body.6.res_layer.2.weight", "body.6.res_layer.3.weight", "body.6.res_layer.4.weight", "body.6.res_layer.4.bias", "body.6.res_layer.4.running_mean", "body.6.res_layer.4.running_var", "body.6.res_layer.5.fc1.weight", "body.6.res_layer.5.fc2.weight", "body.7.shortcut_layer.0.weight", "body.7.shortcut_layer.1.weight", "body.7.shortcut_layer.1.bias", "body.7.shortcut_laye....

----------
little detail:

ckpt loaded doesn't have any key that matches "encoder' and "decoder" required here, https://github.com/yuval-alaluf/hyperstyle/blob/main/models/encoders/psp.py#L46
instead, keys in ckpt are "g", "g_ema", "d", with tensors as follows
ipdb> ckpt['g'].keys()
odict_keys(['style.1.weight', 'style.1.bias', 'style.2.weight', 'style.2.bias', 'style.3.weight', 'style.3.bias', 'style.4.weight', 'style.4.bias', 'style.5.weight', 'style.5.bias', 'style.6.weight', 'style.6.bias', 'style.7.weight', 'style.7.bias', 'style.8.weight', 'style.8.bias', 'input.input', 'conv1.conv.weight', 'conv1.conv.modulation.weight', 'conv1.conv.modulation.bias', 'conv1.noise.weight', 'conv1.activate.bias', 'to_rgb1.bias', 'to_rgb1.conv.weight', 'to_rgb1.conv.modulation.weight', 'to_rgb1.conv.modulation.bias', 'convs.0.conv.weight', 'convs.0.conv.blur.kernel', 'convs.0.conv.modulation.weight', 'convs.0.conv.modulation.bias', 'convs.0.noise.weight', 'convs.0.activate.bias', 'convs.1.conv.weight', 'convs.1.conv.modulation.weight', 'convs.1.conv.modulation.bias', 'convs.1.noise.weight', 'convs.1.activate.bias',
'convs.2.conv.weight', 'convs.2.conv.blur.kernel', 'convs.2.conv.modulation.weight', 'convs.2.conv.modulation.bias', 'convs.2.noise.weight', 'convs.2.activate.bias', 'convs.3.conv.weight', 'convs.3.conv.modulation.weight', 'convs.3.conv.modulation.bias', 'convs.3.noise.weight', 'convs.3.activate.bias', 'convs.4.conv.weight', 'convs.4.conv.blur.kernel', 'convs.4.conv.modulation.weight', 'convs.4.conv.modulation.bias', 'convs.4.noise.weight', 'convs.4.activate.bias', 'convs.5.conv.weight', 'convs.5.conv.modulation.weight', 'convs.5.conv.modulation.bias', 'convs.5.noise.weight', 'convs.5.activate.bias', 'convs.6.conv.weight', 'convs.6.conv.blur.kernel', 'convs.6.conv.modulation.weight', 'convs.6.conv.modulation.bias', 'convs.6.noise.weight', 'convs.6.activate.bias', 'convs.7.conv.weight', 'convs.7.conv.modulation.weight', 'convs.7.conv.modulation.bias', 'convs.7.noise.weight', 'convs.7.activate.bias', 'convs.8.conv.weight', 'convs.8.conv.blur.kernel', 'convs.8.conv.modulation.weight', 'convs.8.conv.modulation.bias', 'convs.8.noise.weight', 'convs.8.activate.bias', 'convs.9.conv.weight', 'convs.9.conv.modulation.weight', 'convs.9.conv.modulation.bias', 'convs.9.noise.weight', 'convs.9.activate.bias', 'convs.10.conv.weight', 'convs.10.conv.blur.kernel', 'convs.10.conv.modulation.weight', 'convs.10.conv.modulation.bias', 'convs.10.noise.weight', 'convs.10.activate.bias', 'convs.11.conv.weight', 'convs.11.conv.modulation.weight', 'convs.11.conv.modulation.bias', 'convs.11.noise.weight', 'convs.11.activate.bias', 'convs.12.conv.weight', 'convs.12.conv.blur.kernel', 'convs.12.conv.modulation.weight', 'convs.12.conv.modulation.bias', 'convs.12.noise.weight', 'convs.12.activate.bias', 'convs.13.conv.weight', 'convs.13.conv.modulation.weight', 'convs.13.conv.modulation.bias', 'convs.13.noise.weight', 'convs.13.activate.bias', 'convs.14.conv.weight', 'convs.14.conv.blur.kernel', 'convs.14.conv.modulation.weight', 'convs.14.conv.modulation.bias', 'convs.14.noise.weight', 'convs.14.activate.bias', 'convs.15.conv.weight', 'convs.15.conv.modulation.weight', 'convs.15.conv.modulation.bias', 'convs.15.noise.weight', 'convs.15.activate.bias', 'to_rgbs.0.bias', 'to_rgbs.0.upsample.kernel', 'to_rgbs.0.conv.weight', 'to_rgbs.0.conv.modulation.weight', 'to_rgbs.0.conv.modulation.bias', 'to_rgbs.1.bias', 'to_rgbs.1.upsample.kernel', 'to_rgbs.1.conv.weight', 'to_rgbs.1.conv.modulation.weight', 'to_rgbs.1.conv.modulation.bias', 'to_rgbs.2.bias', 'to_rgbs.2.upsample.kernel', 'to_rgbs.2.conv.weight', 'to_rgbs.2.conv.modulation.weight', 'to_rgbs.2.conv.modulation.bias', 'to_rgbs.3.bias', 'to_rgbs.3.upsample.kernel', 'to_rgbs.3.conv.weight', 'to_rgbs.3.conv.modulation.weight', 'to_rgbs.3.conv.modulation.bias', 'to_rgbs.4.bias', 'to_rgbs.4.upsample.kernel', 'to_rgbs.4.conv.weight', 'to_rgbs.4.conv.modulation.weight', 'to_rgbs.4.conv.modulation.bias', 'to_rgbs.5.bias', 'to_rgbs.5.upsample.kernel', 'to_rgbs.5.conv.weight', 'to_rgbs.5.conv.modulation.weight', 'to_rgbs.5.conv.modulation.bias', 'to_rgbs.6.bias', 'to_rgbs.6.upsample.kernel', 'to_rgbs.6.conv.weight', 'to_rgbs.6.conv.modulation.weight', 'to_rgbs.6.conv.modulation.bias', 'to_rgbs.7.bias', 'to_rgbs.7.upsample.kernel', 'to_rgbs.7.conv.weight', 'to_rgbs.7.conv.modulation.weight', 'to_rgbs.7.conv.modulation.bias', 'noises.noise_0', 'noises.noise_1', 'noises.noise_2', 'noises.noise_3', 'noises.noise_4', 'noises.noise_5', 'noises.noise_6', 'noises.noise_7', 'noises.noise_8', 'noises.noise_9', 'noises.noise_10', 'noises.noise_11', 'noises.noise_12', 'noises.noise_13',
'noises.noise_14', 'noises.noise_15', 'noises.noise_16'])

**Comment by MISSEY** [comment]
How did you solved this ?

**Comment by MISSEY** [comment]
@yuval-alaluf I am having the same issue with my own w_e4e encoder trained using this repository - https://github.com/omertov/encoder4editing 

This is my command : 

```bash
python scripts/train.py \
    --dataset_type=faces_data \
    --encoder_type=SharedWeightsHyperNetResNet \
    --exp_dir=experiments/hyperstyle \
    --workers=8 \
    --batch_size=8 \
    --test_batch_size=8 \
    --test_workers=8 \
    --val_interval=5000 \
    --save_interval=2000 \
    --lpips_lambda=0.8 \
    --l2_lambda=1 \
    --id_lambda=0 \
    --moco_lambda=0.5 \
    --n_iters_per_batch=5 \
    --max_val_batches=150 \
    --output_size=1024 \
    --load_w_encoder \
    --stylegan_weights /netscratch/smishra/gan_inversion/hyperstyle/pretrained_models/network-snapshot-015974_gan_inv.pt \
    --w_encoder_checkpoint_path /netscratch/smishra/gan_inversion/hyperstyle/pretrained_models/w_encoder.pt
```
Also, https://github.com/yuval-alaluf/hyperstyle/blob/main/models/hyperstyle.py#L145, I couldn't find where e4e is called, is hyperstyle only support psp ?
Thanks in advance
